#!/usr/bin/env bash

source scripts/utilities.sh
source scripts/functions.sh

######## Script ########
PS3='Select an option and press Enter: '
options=("Debian/Ubuntu" "MacOS" "Quit")
select opt in "${options[@]}"
do
  case $opt in
        "Debian/Ubuntu")
            echo ""
            source scripts/ubuntu.sh
            break
            ;;
        "MacOS")
            echo ""
            source scripts/macos.sh
            break
            ;;
        "Quit")
            echo "Bye"
            exit 0
            ;;
        *)
            echo "Invalid option"
            ;;
  esac
done

# Load submodules
print_style "Loading submodules" "info"
git submodule update --init --recursive

# Change default shell to fish
switchToFish

# Install Oh-my-fish
installOMF

# Ruby and colorls
installRubyColorls

# Portainer
# TODO: check
# installPortainer

# Dotfiles
source dotfiles/install

# THE END!
print_style "All done!" "success"
exit 0
